import React from 'react';
import { CssBaseline, Typography } from '@mui/material';
import { PerformanceMetric } from "./components";
import PerformancePage from "./pages/PerformancePage/PerformancePage";

function Home() {
    return (
        <Typography variant="h5" component="h2">
            Home Page
        </Typography>
    );
}

function About() {
    return (
        <Typography variant="h5" component="h2">
            About Page
        </Typography>
    );
}

function App() {
    return (
        <>
            <CssBaseline/>
            <PerformancePage />
            {/*<PerformanceMetric*/}
            {/*    variant={'infoMetricIcon'}*/}
            {/*    metricIcon={<i className="ri-money-dollar-circle-line metric-icon"></i>}*/}
            {/*    content={1000}*/}
            {/*    metricName={'Total Revenue'}*/}
            {/*    tooltip={'Total revenue generated by the company'}*/}
            {/*    subtitle={<>*/}
            {/*        {'$1M per quarter'}*/}
            {/*    </>}*/}
            {/*/>*/}
            {/*<Container maxWidth="md">*/}
            {/*    <Paper style={{ margin: '24px 0', padding: '20px' }}>*/}
            {/*        <Routes>*/}
            {/*            <Route path="/" element={<Home/>}/>*/}
            {/*            <Route path="/about" element={<About/>}/>*/}
            {/*        </Routes>*/}
            {/*    </Paper>*/}
            {/*</Container>*/}
        </>
    );
}

export default App;
