import React, { useState } from 'react';
import './PerformancePage.scss';
import PageMetrics from "../../components/PageMetrics/PageMetrics";
import { TabSwitch } from "../../components";
import { SUMMARY, UTM_LINKS } from "../../utils/constants";
import TabPanel from "../../components/TabSwitch/TabPanel";

export default function PerformancePage(props) {
    const [currentTab, setCurrentTab] = useState(SUMMARY);
    const tabs = [
        {
            label: SUMMARY,
        },
        {
            label: UTM_LINKS,
        },
    ];
    return (
        <div className={'div-performance-page'}>
            <section className={'section-metrics'}>
                <div className={'div-page-title'}>
                    <span className={'section-heading'}>Performance</span>
                    <TabSwitch
                        tabs={tabs}
                        currentTab={currentTab}
                        handleTabChange={(event, newTab) => {
                            setCurrentTab(newTab);
                        }}
                        height={40}
                        width={224}
                    />
                </div>


                <div>
                    <TabPanel index={SUMMARY} value={currentTab}>
                        <PageMetrics
                            leftMetrics={{
                                mainMetric: {
                                    value: 1000,
                                    title: 'Total Revenue'
                                },
                                subMetrics: [{
                                    icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                    value: 10000,
                                    name: 'Total Revenue',
                                    subtitle: <>$1M per quarter</>,
                                    tooltip: 'Total revenue generated by the company'
                                }, {
                                    icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                    value: 1000,
                                    name: 'Total Sales',
                                    subtitle: <>$3M per quarter</>,
                                    tooltip: 'Total sales generated by the company'
                                }]
                            }}
                            rightMetrics={[{
                                icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                value: 10000,
                                name: 'Total Revenue',
                                subtitle: <>$1M per quarter</>,
                                tooltip: 'Total revenue generated by the company'
                            }, {
                                icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                value: 1000,
                                name: 'Total Sales',
                                subtitle: <>$3M per quarter</>,
                                tooltip: 'Total sales generated by the company'
                            }, {
                                icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                value: 1000,
                                name: 'Total Sales',
                                tooltip: 'Total sales generated by the company'
                            }]}
                        />
                    </TabPanel>
                    <TabPanel index={UTM_LINKS} value={currentTab}>
                    </TabPanel>

                </div>
            </section>
        </div>
    );
}
