import React from 'react';
import './PerformancePage.scss';
import PageMetrics from "../../components/PageMetrics/PageMetrics";

export default function PerformancePage(props) {
    return (
        <div className={'div-performance-page'}>
            <section className={'section-metrics'}>
                <span className={'section-heading'}>Performance</span>
                <div style={{ marginTop: 32 }}>
                    <PageMetrics
                        leftMetrics={{
                            mainMetric: {
                                value: 1000,
                                title: 'Total Revenue'
                            },
                            subMetrics: [{
                                icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                value: 10000,
                                name: 'Total Revenue',
                                subtitle: <>$1M per quarter</>,
                                tooltip: 'Total revenue generated by the company'
                            }, {
                                icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                                value: 1000,
                                name: 'Total Sales',
                                subtitle: <>$3M per quarter</>,
                                tooltip: 'Total sales generated by the company'
                            }]
                        }}
                        rightMetrics={[{
                            icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                            value: 10000,
                            name: 'Total Revenue',
                            subtitle: <>$1M per quarter</>,
                            tooltip: 'Total revenue generated by the company'
                        }, {
                            icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                            value: 1000,
                            name: 'Total Sales',
                            subtitle: <>$3M per quarter</>,
                            tooltip: 'Total sales generated by the company'
                        }, {
                            icon: <i className="ri-money-dollar-circle-line metric-icon"></i>,
                            value: 1000,
                            name: 'Total Sales',
                            tooltip: 'Total sales generated by the company'
                        }]}
                    />
                </div>
            </section>
        </div>
    );
}
